# Generated by Django 3.2.4 on 2021-06-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PartsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panorama.room')),
            ],
        ),
    ]
