# Generated by Django 3.2.4 on 2021-06-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartsImage',
            new_name='ComponentImage',
        ),
    ]
