# Generated by Django 3.2.4 on 2021-06-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0002_rename_partsimage_componentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='component', to='panorama.room'),
        ),
    ]
